;;(define-key ac-mode-map (kbd "M-TAB") 'auto-complete)
;;(autoload  'ace-jump-mode  "ace-jump-mode" t)
;;(eval-after-load "ace-jump-mode"  '(ace-jump-mode-enable-mark-sync))
;;(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
;;(define-key global-map (kbd "C-x SPC") 'ace-jump-mode-pop-mark)
